version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm run dev

volumes:
  mongo-data:
